# vim:ft=kitty

## name:     Catppuccin Kitty Mocha
## author:   Catppuccin Org
## license:  MIT
## upstream: https://github.com/catppuccin/kitty/blob/main/themes/mocha.conf
## blurb:    Soothing pastel theme for the high-spirited!

# The basic colors
foreground              #d8e0f0
background              #1a1a24
selection_foreground    #1a1a24
selection_background    #f0d0c8

# Cursor colors
cursor                  #f0d0c8
cursor_text_color       #1a1a24

# URL underline color when hovering with mouse
url_color               #f0d0c8

# Kitty window border colors
active_border_color     #1a1a24

inactive_border_color   #303850
bell_border_color       #e8d098

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #11111b
active_tab_background   #c098e0
inactive_tab_foreground #d8e0f0
inactive_tab_background #181825
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1a1a24
mark1_background #a8b0e8
mark2_foreground #1a1a24
mark2_background #c098e0
mark3_foreground #1a1a24
mark3_background #70b8d0

# The 16 terminal colors

# black
color0 #404860
color8 #505870

# red
color1 #d87a8a
color9 #d87a8a

# green
color2  #98d090
color10 #98d090

# yellow
color3  #e8d098
color11 #e8d098

# blue
color4  #80a8e8
color12 #80a8e8

# magenta
color5  #e8a8d0
color13 #e8a8d0

# cyan
color6  #88d0c0
color14 #88d0c0

# white
color7  #c0c8e0
color15 #a8b0d0

background_tint  0.75
background_image ./backgrounds/dark.png
background_image_layout mirror-tiled

