# vim:ft=kitty

## name: Colorscheme Light

# The basic colors
foreground              #2a2a37
background              #f5f3ee
selection_foreground    #f5f3ee
selection_background    #2a2a37

# Cursor colors
cursor                  #2a2a37
cursor_text_color       #f5f3ee

# URL underline color when hovering with mouse
url_color               #4c6fae

# Kitty window border colors
active_border_color     #ddd9d0
inactive_border_color   #e9e6df
bell_border_color       #b38a3c

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #6f5fa6
active_tab_background   #f5f3ee
inactive_tab_foreground #8a887f
inactive_tab_background #e9e6df
tab_bar_background      #e9e6df

# Colors for marks (marked text in the terminal)
mark1_foreground #f5f3ee
mark1_background #4c6fae
mark2_foreground #f5f3ee
mark2_background #6f5fa6
mark3_foreground #f5f3ee
mark3_background #4a8a7a

# The 16 terminal colors

# black
color0 #8a887f
color8 #a8a69f

# red
color1 #c84053
color9 #c84053

# green
color2  #5f7f3a
color10 #5f7f3a

# yellow
color3  #b38a3c
color11 #b38a3c

# blue
color4  #4c6fae
color12 #4c6fae

# magenta
color5  #6f5fa6
color13 #6f5fa6

# cyan
color6  #4a8a7a
color14 #4a8a7a

# white
color7  #ddd9d0
color15 #e9e6df

background_tint 0.60
background_image ./backgrounds/light.png
background_image_layout mirror-tiled
