# vim:ft=kitty

## name: Colorscheme Light

# The basic colors
foreground              #dcd7ba
background              #1f1f28
selection_foreground    #1f1f28
selection_background    #dcd7ba

# Cursor colors
cursor                  #dcd7ba
cursor_text_color       #1f1f28

# URL underline color when hovering with mouse
url_color               #7e9cd8

# Kitty window border colors
active_border_color     #363646
inactive_border_color   #2a2a37
bell_border_color       #e6c384

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #a89ecb
active_tab_background   #1f1f28
inactive_tab_foreground #727169
inactive_tab_background #2a2a37
tab_bar_background      #2a2a37

# Colors for marks (marked text in the terminal)
mark1_foreground #1f1f28
mark1_background #7e9cd8
mark2_foreground #1f1f28
mark2_background #a89ecb
mark3_foreground #1f1f28
mark3_background #7aa89f

# The 16 terminal colors

# black
color0 #727169
color8 #54546d

# red
color1 #e46876
color9 #e46876

# green
color2  #98bb6c
color10 #98bb6c

# yellow
color3  #e6c384
color11 #e6c384

# blue
color4  #7e9cd8
color12 #7e9cd8

# magenta
color5  #a89ecb
color13 #a89ecb

# cyan
color6  #7aa89f
color14 #7aa89f

# white
color7  #363646
color15 #2a2a37

background_tint 0.60
background_image ./backgrounds/light.png
background_image_layout mirror-tiled
