;; extends 

(("import" @include) (#set! conceal "i"))
(("while" @repeat) (#set! conceal "W"))
(("class" @keyword) (#set! conceal "c"))
(("assert" @keyword) (#set! conceal "?"))
(("global" @keyword) (#set! conceal "G"))
(("with" @keyword) (#set! conceal "w"))
(("and" @keyword.operator) (#set! conceal "&"))
(("break" @keyword) (#set! conceal "B"))
(("del" @keyword) (#set! conceal "D"))
(("else" @conditional) (#set! conceal "e"))
((call function: (identifier) @function.builtin (#eq? @function.builtin "print")) (#set! conceal "p"))
((yield ("from") @keyword) (#set! conceal "F"))
(("continue" @keyword) (#set! conceal "C"))
(("def" @keyword.function) (#set! conceal "f"))
((import_from_statement ("from") @include) (#set! conceal "f"))
(("or" @keyword.operator) (#set! conceal "|"))
(("if" @conditional) (#set! conceal "?"))
(("for" @repeat) (#set! conceal "F"))
(("yield" @keyword) (#set! conceal "Y"))
(("return" @keyword) (#set! conceal "R"))
(("not" @keyword.operator) (#set! conceal "!"))
(("lambda" @include) (#set! conceal "λ"))
(("elif" @conditional) (#set! conceal "e"))
(("pass" @keyword) (#set! conceal "P"))
