FROM docker.io/archlinux/archlinux:latest
ENV NAME=arch-toolbox VERSION=rolling
LABEL com.github.containers.toolbox="true" \
  name="$NAME" \
  version="$VERSION"
RUN pacman -Syu --noconfirm \
  && pacman -S sudo --noconfirm \
  && pacman -Scc --noconfirm \
  && echo "%wheel ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/toolbox
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
RUN mkdir .build
COPY ./install-packages.sh .build/install-packages.sh
RUN bash .build/install-packages.sh
CMD ["bash"]

