# -- Fix odd behaviors in IntelliJ IDEs --
#! Fix focus issues when dialogs are opened or closed
windowrulev2 = windowdance,class:^(jetbrains-.*)$,floating:1
#! Fix splash screen showing in weird places and prevent annoying focus takeovers
windowrulev2 = center,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(splash)$,floating:1
windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^(splash)$,floating:1

#! Center popups/find windows
windowrulev2 = center,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrulev2 = stayfocused,class:^(jetbrains-.*)$,title:^( )$,floating:1
windowrulev2 = noborder,class:^(jetbrains-.*)$,title:^( )$,floating:1
#! Disable window flicker when autocomplete or tooltips appear
windowrulev2 = nofocus,class:^(jetbrains-.*)$,title:^(win.*)$,floating:1

# -- nxthelper terminal windows
windowrulev2 = float, title:(nxthelper)
windowrulev2 = size 50% 50%, title:(nxthelper)
windowrulev2 = workspace special:nxthelper,title:^(nxthelper)$
bind = CTRL_L, Period, exec, hyprctl dispatch togglespecialworkspace nxthelper

# -- generic rule for windows having title starting with "floating"
windowrulev2 = float, title:^floating
windowrulev2 = size 40% 40%,title:(^floating)

# -- pavucontrol 
