#! /usr/bin/env sh

if [ -x $(command -v exa) ]; then
  alias ls='exa -a'
  alias ll='exa -la'
else
  alias ls='ls -A --color=auto'
  alias ll='ls -l'
fi

alias cc='xclip -sel clip'

alias nvms='source /usr/share/nvm/init-nvm.sh'

## Git Aliases
alias gaa='git add .'
alias ga='git add'
alias gb='git branch -a'
alias gc='git commit -am'
alias gs='git status'
alias gss='git status -s'

# git flow aliases
alias gf='git flow'
alias gfff='git flow feature finish'
alias gffs='git flow feature start'
alias gffp='git flow feature publish'
