#! /usr/bin/env sh

if [ -x $(command -v exa) ]; then
  alias ls='exa'
  alias ll='exa -la'
else
  alias ls='ls -A --color=auto'
  alias ll='ls -l'
fi

alias kx='kubie ctx'
alias kn='kubie ns'

alias nv='nvim'

alias k='kubectl'

alias tel='telepresence'

alias cc='xclip -sel clip'

alias nvms='source /usr/share/nvm/init-nvm.sh'

## Git Aliases
alias gaa='git add .'
alias ga='git add -p'
alias gb='git branch -a'
alias gc='git commit -am'
alias gs='git status'
alias gss='git status -s'

# git flow aliases
alias gfff='git flow feature finish'
alias gffs='git flow feature start'
alias gffp='git flow feature publish'
alias gfbs='git flow bugfix start'
alias gfbf='git flow bugfix finish'
alias gfbp='git flow bugfix publish'
alias gf='git flow'
