#! /usr/bin/env sh

# nvim() {
#  $HOME/builds/nvim.appimage "$@"
# }

pnpm() {
  if [ $1 = "peer" ]; then
    PKG=$2
    shift 1;
    command pnpm i $(npm info "$PKG@latest" peerDependencies --json | sed 's/[\{\},]//g ; s/: /@/g' | xargs) $@
  else
    command pnpm $@
  fi
}

_fzf_complete_make() {
  _fzf_complete --multi --reverse --prompt="target> " -- "make ${@:2}" < <(grep -iE '^[^.].*:\s+' ./Makefile | awk -F':' '{print $1}' | uniq)
}

_fzf_complete_prun() {
  _fzf_complete --multi --reverse --prompt="package.json script> " -- "pnpm run ${@:2}" < <(cat ./package.json| jq '.scripts'  | grep -i '"' | awk '{print $1}' | sed 's/:$//g' | sed 's/"//g')
}

# _fzf_complete_sample() {
#   _fzf_complete --multi --reverse --prompt="target> " -- "$@" < <()
# }

list() {
  telepresence list -n hotspot
}

telenv() {
 printenv | grep -i telepresence | awk '{print "export " $1}' > ~/.env
 # ktunnel inject deployment ${1:-api-dev} ${2:-3000}
}

intercept() {
  [ -f ~/.env ] && rm ~/.env 
  telepresence intercept app-nxtcoder17 -p 3000:80 --mount=/tmp/nxtcoder17 -n hotspot zsh
  # --mapped-namespaces hotspot zsh 
}

# intercept2() {
#   telepresence intercept api-dev -p 3000:80 --mount=/tmp/nxtcoder17 -n dev-hotspot ktunnel -- inject deployment -n dev-hotspot ${1:-api-dev} ${2:-3000} 
# }
