# vim: set ft=conf:
font_family      Agave Nerd Font Regular
# font_family      ComicCodeLigatures Nerd Font SemiBold
bold_font        Agave Nerd Font Bold
# italic_font      Monaspace Radon Var SemiBold Italic
italic_font      Monaspace Radon Var Medium Italic
# bold_italic_font Monaspace Radon Var SemiBold Italic
bold_italic_font Monaspace Radon Var Medium Italic

# for laptop
font_size 10.5

modify_font cell_width 110%
modify_font cell_height +10px

# for desktop
# font_size 10

font_features MonaspaceRadonVar-LightItalic +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
font_features MonaspaceRadonVar-BoldItalic  +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
