# vim: set ft=conf:
font_family ComicCodeLigatures-Medium
bold_font ComicCodeLigatures-Bold
# italic_font ComicCodeLigatures-MedIta
italic_font VictorMono NFM SemiBold Italic
# bold_italic_font ComicCodeLigatures-BoldItalic
bold_italic_font VictorMono NFM Bold Italic

# for laptop
font_size 10

# # font_family      ComicCodeLigatures Nerd Font SemiBold
# # bold_font        ComicCodeLigatures Nerd Font Bold
# # italic_font      Monaspace Radon Var SemiBold Italic
# # bold_italic_font Monaspace Radon Var Bold Italic
#
# # for laptop
# font_size 10
#
# # for desktop
# # font_size 10
#
# font_features MonaspaceRadonVar-LightItalic +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
# font_features MonaspaceRadonVar-BoldItalic  +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
#
# # symbol_map U+E0A0-U+E0A3,U+E0B0-U+E0B3 Monaspace Radon Var SemiBold
