# vim: set ft=conf:

font_family ComicShannsMono Nerd Font Mono
# font_family VictorMono NFM SemiBold
# bold_font ComicShannsMono Nerd Font Mono Bold
# italic_font SeriousShanns Nerd Font Mono It
# bold_italic_font SeriousShanns Nerd Font Mono Bd It

italic_font VictorMono NFM SemiBold Italic
bold_italic_font VictorMono NFM Bold Italic

# for laptop
font_size 11

# modify_font cell_width 101%
# modify_font cell_height +4px
