# vim: set ft=conf:
font_family ComicCodeLigatures-SemiBold
bold_font ComicCodeLigatures-Bold
italic_font ComicCodeLigatures-MedIta
# italic_font VictorMono NFM SemiBold Italic
bold_italic_font ComicCodeLigatures-BoldItalic
# bold_italic_font VictorMono NFM Bold Italic

# for laptop
font_size 12
