# vim: set ft=conf:
font_family      IosevkaTerm NF
bold_font        IosevkaTerm NF Bold
italic_font      IosevkaTerm NF Italic
bold_italic_font IosevkaTerm NF Bold Italic

font_size 12

modify_font cell_width 110%
modify_font cell_height +2px
#
# font_features MonaspaceRadonVar-LightItalic +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
# font_features MonaspaceRadonVar-BoldItalic  +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
