# vim: set ft=conf:

# font_family      Kode Mono Medium
font_family      Lotion Regular
italic_font      Monaspace Radon Var Regular
bold_font        Lotion Medium
bold_italic_font Monaspace Radon Var Bold

# for monitor
# font_size 11
font_size 10

font_features MonaspaceKryptonVar-Regular       +ss01 +ss02 +ss03 +ss04 +ss05 -ss06 +ss07 -ss08 +dlig +lig +calt
font_features MonaspaceRadonVar-Regular       +ss01 +ss02 +ss03 +ss04 +ss05 -ss06 +ss07 -ss08 +dlig +lig +calt
font_features MonaspaceKryptonVar-RegularItalic +ss01 +ss02 +ss03 +ss04 +ss05 -ss06 +ss07 -ss08 +dlig +calt
font_features MonaspaceRadonVar-Bold        +ss01 +ss02 +ss03 +ss04 +ss05 -ss06 +ss07 -ss08 +dlig +calt
font_features MonaspaceKryptonVar-Medium       +ss01 +ss02 +ss03 +ss04 +ss05 -ss06 +ss07 -ss08 +dlig +lig +calt
font_features MonaspaceKryptonVar-BoldItalic  +ss01 +ss02 +ss03 +ss04 +ss05 -ss06 +ss07 -ss08 +dlig +calt
