# vim: set ft=conf:

# font_family      Kode Mono Medium
font_family      Lotion Regular
italic_font      Lotion Regular Italic
bold_font        Lotion Semibold
bold_italic_font Lotion Bold Italic

# for monitor
# font_size 11
font_size 13
