# vim: set ft=conf:

### font-group: Github Monaspace
font_family      Monaspace Krypton Var Light
italic_font      Monaspace Krypton Var Light Italic
bold_font        Monaspace Krypton Var Bold
bold_italic_font Monaspace Krypton Var Bold Italic


# read more @ https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.font_features
font_features MonaspaceKryptonVar-Light       +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +lig
font_features MonaspaceKryptonVar-LightItalic +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig 
font_features MonaspaceKryptonVar-Bold        +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig 
font_features MonaspaceKryptonVar-BoldItalic  +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig 
