# vim: set ft=conf:

### font-group: Github Monaspace
font_family      Monaspace Krypton Var Regular
italic_font      Monaspace Krypton Var Regular Italic
bold_font        Monaspace Krypton Var Bold
bold_italic_font Monaspace Krypton Var Bold Italic

# for monitor
font_size 12.47

# read more @ https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.font_features
font_features MonaspaceKryptonVar-Regular       +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +lig +calt
font_features MonaspaceKryptonVar-RegularItalic +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
font_features MonaspaceKryptonVar-Bold        +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
font_features MonaspaceKryptonVar-BoldItalic  +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt

