# vim: set ft=conf:


### font-group: operator mono lig
font_family      MonoLisa Regular
# bold_font        
# italic_font      Operator Mono Lig Medium Italic
# bold_italic_font Operator Mono Bold Italic Nerd Font Complete

font_size 9
