# vim: set ft=conf:

### font-group: operator mono lig
font_family      Operator Mono Lig Medium
bold_font        Operator Mono Bold Nerd Font Complete
italic_font      Operator Mono Lig Medium Italic
bold_italic_font Operator Mono Bold Italic Nerd Font Complete

