# vim: set ft=conf:

# font_family Recursive Mn Csl St Med
# bold_font RecMonoSmCasual Nerd Font Mono Bold
# italic_font RecMonoSmCasual Nerd Font Mono Italic
# bold_italic_font RecMonoSmCasual Nerd Font Mono Bold Italic

font_family Recursive Mono Casual Static
bold_font Recursive Mono Casual Bold
italic_font Recursive Mono Casual Medium Italic
bold_italic_font Recursive Mono Casual Bold Italic

font_features Recursive +dlig +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +ss09 +calt -ss10

# bold_font SeriousShanns Nerd Font Mono Bd
# italic_font Victor Mono Medium Italic
# bold_italic_font Victor Mono Bold Italic


# for laptop
# font_size 10.5

# for monitor
font_size 12

# modify_font cell_width 101.5%
modify_font cell_height +5px
