# vim: set ft=conf:

# font_family Recursive Mn Csl St Med
# bold_font RecMonoSmCasual Nerd Font Mono Bold
# italic_font RecMonoSmCasual Nerd Font Mono Italic
# bold_italic_font RecMonoSmCasual Nerd Font Mono Bold Italic

font_family Recursive Mono Casual Medium
bold_font Recursive Mono Casual Bold
italic_font Recursive Mono Casual Medium Italic
bold_italic_font Recursive Mono Casual Bold Italic

# bold_font SeriousShanns Nerd Font Mono Bd
# italic_font Victor Mono Medium Italic
# bold_italic_font Victor Mono Bold Italic


# for laptop
# font_size 10.5

# for monitor
font_size 11.5

# modify_font cell_width 101.5%
# modify_font cell_height +6px
