# vim: set ft=conf:

# font_family SeriousShanns Nerd Font Mono
font_family Serious Shanns
bold_font ComicCodeLigatures Medium

# italic_font VictorMono NFM SemiBold Italic
# bold_italic_font VictorMono NFM Bold Italic

# for laptop
font_size 10

# modify_font cell_width 101%
modify_font cell_height +4px

italic_font      Monaspace Radon Var Medium Italic
bold_italic_font Monaspace Radon Var Bold Italic

font_features MonaspaceRadonVar-LightItalic +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt
font_features MonaspaceRadonVar-BoldItalic  +ss01 +ss02 +ss03 +ss04 +ss05 +ss06 +ss07 +ss08 +dlig +calt

# : ; = f
symbol_map U+003A,U+003B,U+003D,U+0066 "Monaspace Radon Var Medium"
