local M = {}

M.color_palette = {
  -- default set, generated by chatgpt
  black = "#1E1E1E",
  red = "#d65e84",
  green = "#B3CC57",
  -- yellow = "#ECC48D",
  yellow = "#b5ba84",
  blue = "#79a4c9",
  magenta = "#B189C6",
  -- cyan = "#6ECFCF",
  -- cyan = "#86bdbd",
  cyan = "#7fa5b3",
  -- white = "#e3d8c3",
  white = "#d9cbb2",
  pink = "#FFB6C1",
  orange = "#ad9679",

  -- custom colors
  sky_blue = "#64bbed",
  cyan_bright = "#65f7e1",
  -- sky_blue = "#86bdbd",
  -- sky_blue = "#91c2c2",
  light_green = "#cfe3d3",
  dark_green = "#152d2e",

  non_text = "#3e474d",

  shades_of_cyan_blue = {
    bright_cyan = "#00FFFF",
    sky_blue = "#87CEEB",
    turquoise = "#40E0D0",
    electric_cyan = "#00FFD1",
    celeste = "#B2FFFF",
    cyan_cornflower_blue = "#188BC2",
    dark_cyan = "#008B8B",
    teal = "#008080",
    aqua_marine = "#7FFFD4",
    cadet_blue = "#5F9EA0",
  },
}

local light_constrasts = {
  blue1 = "#e4eaed",
  green1 = "#ddeddf",
  green9 = "#576158",
}

local highlights_tabby = {
}

-- Default options
require("nightfox").setup({
  options = {
    -- Compiled file's destination location
    compile_path = vim.fn.stdpath("cache") .. "/nightfox",
    compile_file_suffix = "_compiled", -- Compiled file suffix
    transparent = true,             -- Disable setting background
    terminal_colors = true,          -- Set terminal colors (vim.g.terminal_color_*) used in `:terminal`
    dim_inactive = false,            -- Non focused panes set to alternative background
    module_default = true,           -- Default enable value for modules
    colorblind = {
      enable = true,                 -- Enable colorblind support
      simulate_only = true,          -- Only show simulated colorblind colors and not diff shifted
      severity = {
        protan = 0,                  -- Severity [0,1] for protan (red)
        deutan = 0,                  -- Severity [0,1] for deutan (green)
        tritan = 0,                  -- Severity [0,1] for tritan (blue)
      },
    },
    styles = {          -- Style to be applied to different syntax groups
      comments = "italic", -- Value is any valid attr-list value `:help attr-list`
      conditionals = "italic",
      constants = "italic",
      functions = "NONE",
      keywords = "italic",
      numbers = "NONE",
      operators = "NONE",
      strings = "NONE",
      types = "NONE",
      variables = "NONE",
    },
    inverse = { -- Inverse highlight for different types
      match_paren = false,
      visual = false,
      search = false,
    },
    modules = { -- List of various plugins and additional options
      -- ...
    },
  },
  palettes = {
    -- Palettes are the base color defines of a colorscheme.
    -- You can override these palettes for each colorscheme defined by nightfox.

    -- source: https://github.com/EdenEast/nightfox.nvim#customize-palettes-and-groups

    -- Each palette defines these colors:
    -- black, red, green, yellow, blue, magenta, cyan, white, orange, pink
    -- NOTE: These colors have 3 shades: base, bright, and dim.
    -- blue = { base = "#4d688e", bright = "#4e75aa", dim = "#485e7d" },
    -- or
    -- blue = "#4d688e" -- Defining just a color defines it's base color.

    -- A palette also defines the following:
    --   bg0, bg1, bg2, bg3, bg4, fg0, fg1, fg2, fg3, sel0, sel1, comment

    -- Everything defined under `all` will be applied to each style.
    nightfox = M.color_palette,
  },
  specs = {
    nightfox = {
      syntax = {
        -- keyword = "magenta",
        keyword = "magenta",
      },
    },
  },
  groups = {
    nightfox = {
      MatchParen = {
        fg = M.color_palette.shades_of_cyan_blue.aqua_marine,
      },

      Constant = {
        fg = M.color_palette.orange,
      },

      ["@parameter"] = {
        fg = M.color_palette.cyan,
      },

      ["@keyword.return"] = {
        -- italic = "true",
        undercurl = "true",
        link = "Keyword",
      },

      -- ["FzfLuaCursorLine"] = {
      --   bg = M.color_palette.dark_green,
      -- },
      --
      ["@function.builtin"] = {
        link = "Keyword",
      },

      ["@function.method"] = {
        link = "@method",
      },

      ["@function.macro"] = {
        link = "@method",
      },

      ["@function.method.call"] = {
        fg = M.color_palette.sky_blue,
      },

      ["@type.builtin"] = {
        link = "@type",
      },

      ["@namespace"] = {
        fg = M.color_palette.sky_blue,
      },
      ["@variable"] = {
        fg = M.color_palette.light_green,
      },
      ["@variable.builtin"] = {
        fg = M.color_palette.light_green,
      },
      ["@text.uri"] = {
        -- fg = M.color_palette.sky_blue,
        fg = M.color_palette.orange,
      },

      ["@method"] = {
        fg = M.color_palette.cyan_bright,
      },

      ["@method.call"] = {
        fg = M.color_palette.cyan,
      },

      FzfLuaBorder = {
        link = "LineNr",
      },

      CursorLine = {
        bg = "#0c2236",
      },

      NonText = {
        fg = M.color_palette.non_text,
      },
      SpecialKey = {
        fg = M.color_palette.non_text,
      },
      Whitespace = {
        fg = M.color_palette.non_text,
      },
    },
    dayfox = {
      MatchParen = {
        bg = "#dadee0",
        -- fg = "#4d616b",
      },

      Cursor = {
        -- bg = "#aec3cf",
        fg = "#dadee0",
      },

      Normal = {
        bg = "#FFFFFF",
      },

      Visual = {
        bg = "#dadee0",
        -- fg = "#aec3cf",
      },

      Pmenu = {
        -- bg = "dadee0",
        bg = "#e4eaed",
      },
      CursorLine = {
        bg = "#a8cfe3",
      },
      LineNr = {
        fg = "#4d616b",
      },

      ["@function.call"] = {
        bg = light_constrasts.green1,
        fg = light_constrasts.green9,
      },
    },
  },
})

-- setup must be called before loading
vim.cmd("colorscheme nightfox")
