backend = "xrender";

# blur:
# {
#   method = "gaussian";
#   size = 20;
#   deviation = 20;
#   kern = "3x3box";
#   method = "kawase";
#   strength = 2;
# };

active-opacity: 0.995;
fading = true;
fade-in-step = 0.0066;
fade-out-step = 0.01;
fade-delta = 1;

unredir-if-possible = false;
vsync = true;

# blur-background-exclude = [ "class_g = 'jetbrains-idea'", "class_g = 'firefoxdeveloperedition'" ]
# focus-background-exclude = [ "class_g = 'jetbrains-idea'", "class_g = 'firefoxdeveloperedition'" ]
# fade-exclude = [ "class_g = 'jetbrains-idea'" ];
# opacity-exclude = [ "class_g = 'firefoxdeveloperedition'" ]
# active-exclude = [ "class_g = 'firefoxdeveloperedition'" ]
opacity-rule = [
  "99:class_g = 'firefoxdeveloperedition'"
]
