preload = /home/nxtcoder17/workspace/nxtcoder17/jeera-rice/wallpapers/dark/never-settle/never-settle-glassified.jpg
wallpaper = , /home/nxtcoder17/workspace/nxtcoder17/jeera-rice/wallpapers/dark/never-settle/never-settle-glassified.jpg
