# vim: set ft=i3config:

# colors
set $transparent    #00000000
set $colorWhite     #eff1f5
set $colorBlack     #16161d
set $colorRed       #db5c5c

# group										 border			 background		text			indicator		childborder
client.focused						 #6687cc		 #364A82			#c0caf5		#9aa5ce			#6687cc
client.focused_inactive		 #16161d		 #16161d			#c0caf5		#16161d			#16161d
client.unfocused					 #16161d		 #16161d			#c0caf5		#16161d			#16161d

bar {
	status_command i3blocks
	i3bar_command i3bar -t
	position top
	mode hide
	modifier $mod

	# font pango: Operator Mono Lig Book Bold 12
	font pango: Comic Code Ligatures Medium 10

	# setting from i3blocks
	separator_symbol " "

	workspace_buttons yes

	binding_mode_indicator no

	colors {
		background $bg2
		# textcolor for the bar
		statusline $fg

		#	 ColorClass			  Border			    Background	Foreground Text
    # focused_workspace   $transparent    $fg2        $bg2
    focused_workspace   $transparent    $colorBlack        $colorWhite
		# inactive_workspace  $transparent    $bg					$fg
		inactive_workspace  $transparent    $transparent					$colorBlack
		urgent_workspace    $transparent    $colorRed				$transparent
	}
}
