# vim: set ft=i3config:

# colors
set $transparent    #00000000
set $colorWhite     #eff1f5
set $colorBlack     #16161d
set $colorRed       #db5c5c
set $colorGreen #e6f2e8

# group										 border			 background		text			indicator		childborder
client.focused						 #6687cc		 #364A82			#c0caf5		#9aa5ce			#6687cc
client.focused_inactive		 #16161d		 #16161d			#c0caf5		#16161d			#16161d
client.unfocused					 #16161d		 #16161d			#c0caf5		#16161d			#16161d

set $bg "#2e4270"
set $bg2 "#152a47"
set $fg "#86bd8e"
set $fg2 "#abd0d9"
set $bg3 "#c791ab"


bar {
	status_command i3blocks
	i3bar_command i3bar -t
	position top
	mode hide
	modifier $mod

	# font pango: Operator Mono Lig Book Bold 12
	font pango: Comic Code Ligatures Medium 9

	# setting from i3blocks
	separator_symbol " "

	workspace_buttons yes

	binding_mode_indicator no

	colors {
		# background $transparent
		background $colorWhite
		# textcolor for the bar
		statusline $fg

		#	 ColorClass			  Border		      Background	      Foreground (text)
    focused_workspace   $transparent    $colorBlack      $colorWhite
    active_workspace    $transparent    $fg              $colorGreen
		inactive_workspace  $transparent    $colorGreen			 $fg
		urgent_workspace    $transparent    $colorRed				$transparent
	}
}
