# Starting gnome keyring daemon
# eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
# export SSH_AUTH_SOCK

# source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

libinput-gestures-setup start

# X Resources
xrdb -merge ~/.Xresources
xrdb -load ~/.Xresources

keyboard-defaults.sh

redshift -O 3000

exec i3
