#! /usr/bin/env sh

for dir in $(command ls -d */ | xargs -0)
do
  if [ "$dir" = "node/" ]; then
    [ -d $XDG_CONFIG_HOME/npm ] || cp -r node/npmrc $XDG_CONFIG_HOME/npm/npmrc
  else
    stow -t $HOME $dir
  fi
done
