# vim: set ft=conf:

### font-group: operator mono lig
# font_family      Operator Mono Lig Medium
# bold_font        Operator Mono Bold Nerd Font Complete
# italic_font      Operator Mono Lig Medium Italic
# bold_italic_font Operator Mono Bold Italic Nerd Font Complete

### font-group: Comic Code Ligatures
# font_family      ComicCodeLigatures-Medium
# bold_font        ComicCodeLigatures-Bold
# italic_font      ComicCodeLigatures-MedIta
# bold_italic_font ComicCodeLigatures-BoldItalic
#
# font_family      Comic Code Ligatures Medium Nerd Font Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Pomicons Plus Font Logos Plus Weather Icons
# bold_font        Comic Code Ligatures Bold Nerd Font Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Pomicons Plus Font Logos Plus Weather Icons
# # italic_font      Comic Code Ligatures Med Ita Nerd Font Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Pomicons Plus Font Logos Plus Weather Icons
# # bold_italic_font Comic Code Ligatures BoldItalic Nerd Font Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Pomicons Plus Font Logos Plus Weather Icons
#
# italic_font      Maple Mono NF Italic
# bold_italic_font Maple Mono NF Bold Italic

### font-group: Recursive Mono Casual
# font_family      RecursiveMonoCslSt-Regular
# bold_font        RecursiveMonoCslSt-Bold
# italic_font      RecursiveMonoLnrSt-Italic
# bold_italic_font RecursiveMonoLnrSt-BdItalic

font_family      Monaspace Radon Var Light
italic_font      Monaspace Radon Var Light Italic
bold_font        Monaspace Radon Var Bold
bold_italic_font Monaspace Radon Var Bold Italic

font_features MonaspaceRadonVar-Light       calt ss01 ss02 ss03 ss04 ss05 ss08 dlig
font_features MonaspaceRadonVar-LightItalic calt ss01 ss02 ss03 ss04 ss05 ss08 dlig
font_features MonaspaceRadonVar-Bold        calt ss01 ss02 ss03 ss04 ss05 ss08 dlig
font_features MonaspaceRadonVar-BoldItalic  calt ss01 ss02 ss03 ss04 ss05 ss08 dlig

font_size 16.0
modify_font cell_height +6px
modify_font baseline -2

font_size 10.30
adjust_line_height 4
# adjust_column_width 1

disable_ligatures never

# Cursor Customization
# cursor #cccccc

shell fish

# TERM env
term xterm-256color
# term xterm-kitty

background_opacity 0.8
# background_image "/home/nxtcoder17/me/jeera-rice/wallpapers/gray-patterns-6K.jpg"


# stops asking for confirmation on close
confirm_os_window_close 0

enable_audio_bell no

# INFO: DO NOT use quotes to wrap theme name, kitty will just not work
include ./themes/nightfox.conf

# kitty_mod alt
# map kitty_mod+t new_tab_with_cwd

map ctrl+shift+w no_op
