# kitty macos only config

shell /opt/homebrew/bin/fish

macos_option_as_alt left

# maps `cmd + NUM` to send `alt + NUM`
map cmd+1 send_text all \x1b1
map cmd+2 send_text all \x1b2
map cmd+3 send_text all \x1b3
map cmd+4 send_text all \x1b4
map cmd+5 send_text all \x1b5
map cmd+6 send_text all \x1b6
map cmd+7 send_text all \x1b7
map cmd+8 send_text all \x1b8
map cmd+9 send_text all \x1b9
map cmd+0 send_text all \x1b0

# maps `cmd + shift + NUM` to send `alt + shift + NUM`
map cmd+shift+1 send_text all \x1b!
map cmd+shift+2 send_text all \x1b@
map cmd+shift+3 send_text all \x1b#
map cmd+shift+4 send_text all \x1b$
map cmd+shift+5 send_text all \x1b%
map cmd+shift+6 send_text all \x1b^
map cmd+shift+7 send_text all \x1b&
map cmd+shift+8 send_text all \x1b*
map cmd+shift+9 send_text all \x1b(
map cmd+shift+0 send_text all \x1b)
