# kitty_mod alt

map alt+shift+h move_window left
map alt+shift+j move_window bottom
map alt+shift+k move_window top
map alt+shift+l move_window right

map alt+h neighboring_window left
map alt+j neighboring_window bottom
map alt+k neighboring_window top
map alt+l neighboring_window right

map ctrl+a>h neighboring_window left
map ctrl+a>j neighboring_window bottom
map ctrl+a>k neighboring_window top
map ctrl+a>l neighboring_window right

map alt+1 goto_tab 1
map alt+2 goto_tab 2
map alt+3 goto_tab 3
map alt+4 goto_tab 4
map alt+5 goto_tab 5
map alt+6 goto_tab 6
map alt+7 goto_tab 7
map alt+8 goto_tab 8
map alt+9 goto_tab 9
map alt+0 goto_tab 10
map alt+n next_tab
map alt+p prev_tab
map alt+tab toggle_tab all

map alt+shift+1 noop
map alt+shift+2 noop
map alt+shift+3 noop
map alt+shift+4 noop
# map alt+shift+5 goto_tab 5
# map alt+shift+6 goto_tab 6
# map alt+shift+7 goto_tab 7
# map alt+shift+8 goto_tab 8
# map alt+shift+9 goto_tab 9
# map alt+shift+0 goto_tab 10

map ctrl+a>c new_tab_with_cwd
map ctrl+a>, set_tab_title

enabled_layouts splits:split_axis=horizontal,stack

map ctrl+a>- launch --add-to-session=. --cwd=current --location=hsplit
map ctrl+a>\ launch --add-to-session=. --cwd=current --location=vsplit
map ctrl+a>q close_window

map ctrl+a>r start_resizing_window

map ctrl+shift+h resize_window narrower
map ctrl+shift+l resize_window wider
map ctrl+shift+k resize_window taller 
map ctrl+shift+j resize_window shorter
# reset all windows in the tab to default sizes
# map ctrl+home resize_window reset

map ctrl+alt+t goto_layout tall
map ctrl+a>z combine : toggle_layout stack : scroll_prompt_to_bottom

map ctrl+alt+s launch --allow-remote-control
  \ kitty +kitten broadcast
  \ --match-tab state:focuseu
  \ --end-session esc

# scrollback_pager nvim -
scrollback_pager nvim - -c "set nonumber nolist showtabline=0 foldcolumn=0 laststatus=0" -c "silent w! /tmp/kitty_scrollback_buffer | nnoremap q <Cmd>:qall<CR> | bd! | term head -c -1 /tmp/kitty_scrollback_buffer"

map ctrl+a>i show_scrollback

# kitty Sessions
tab_bar_filter session:~ or session:^$
# tab_title_template "{(session_name or tab.active_wd.rsplit('/', 1)[-1]) + ' #' if layout_name == 'stack' else '  '}"
# tab_title_template "{(tab.title or session_name or tab.active_wd.rsplit('/', 1)[-1])}"
# active_tab_title_template "{'[' + session_name + '] ' + (title or tab.active_wd).rsplit('/', 1)[-1] + (' *Z' if layout_name == 'stack' else '')}"
# active_tab_title_template "{fmt.bg.default}{fmt.fg.default} [{title}{' *Z' if layout_name == 'stack' else ''}] "

tab_bar_style             separator
tab_bar_min_tabs          2
tab_separator             " "

tab_title_template              " {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title} ({tab.active_exe}){' [🔍]' if layout_name == 'stack' else ''} "
# active_tab_title_template       "{fmt.fg._83b6af}{fmt.bg.default}   {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title}{' []' if layout_name == 'stack' else ''} "
active_tab_title_template       "  {index}:{f'{title[:6]}…{title[-6:]}' if title.rindex(title[-1]) + 1 > 25 else title} ({tab.active_exe}){' [🔍]' if layout_name == 'stack' else ''} "


allow_remote_control yes

# Reference on how to send_text
#map ctrl+shift+s save_as_session --match='session:.' --use-foreground-process --relocatable

# map ctrl+shift+s launch --type=tab --allow-remote-control ~/.config/kitty/scripts/kitty-session-save.sh
# map ctrl+shift+s save_as_session --use-foreground-process --relocatable
# map ctrl+a>s launch --type=tab --allow-remote-control ~/.config/kitty/scripts/kitty-session-select.sh
map f1 set_window_title
map f2 save_as_session --use-foreground-process --relocatable
