# vim: set ft=conf:

# include ./fonts/monaspace-radon.conf
include ./fonts/comic-code-ligatures.conf

disable_ligatures never

# Cursor Customization
# cursor #cccccc

shell fish

# TERM env
term xterm-256color

background_opacity 0.4

# stops asking for confirmation on close
confirm_os_window_close 0

enable_audio_bell no

# INFO: DO NOT use quotes to wrap theme name, kitty will just not work
# include ./themes/nightfox.conf
include ./themes/nightfox.conf

# kitty_mod alt
# map kitty_mod+t new_tab_with_cwd

map ctrl+shift+w no_op
