map ctrl+shift+s launch --type=overlay --title kitty-session-save --allow-remote-control ~/.config/kitty/scripts/kitty-session-save.sh
map ctrl+shift+r launch --type=overlay --title kitty-session-select --allow-remote-control ~/.config/kitty/scripts/kitty-session-select.sh
