# name: 'Catppuccin "Mocha"'
# url: 'https://github.com/catppuccin/fish'
# preferred_background: "#1a1a24"

set -gx fish_color_normal "#d8e0f0"
set -gx fish_color_command "#80a8e8"
set -gx fish_color_param "#d8e0f0"
set -gx fish_color_keyword "#d87a8a"
set -gx fish_color_quote "#70b8d0"
set -gx fish_color_redirection "#e8a8d0"
set -gx fish_color_end "#e8b088"
set -gx fish_color_comment "#7880a0"
set -gx fish_color_error "#d87a8a"
set -gx fish_color_gray "#606880"
set -gx fish_color_selection --background="#303850"
set -gx fish_color_search_match --background="#303850"
set -gx fish_color_option "#e8b8b8"
set -gx fish_color_operator "#e8a8d0"
set -gx fish_color_escape "#e098a8"
set -gx fish_color_autosuggestion "#606880"
set -gx fish_color_cancel "#d87a8a"
set -gx fish_color_cwd "#88d0c0"
set -gx fish_color_user "#e8d098"
set -gx fish_color_host "#80a8e8"
set -gx fish_color_host_remote "#98d090"
set -gx fish_color_status "#d87a8a"
set -gx fish_pager_color_progress "#606880"
set -gx fish_pager_color_prefix "#e8a8d0"
set -gx fish_pager_color_completion "#d8e0f0"
set -gx fish_pager_color_description "#606880"
set -gx fish_color_valid_path "#d8e0f0"
